name: build

on:
  push:
    branches: [ master, 'feature**' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ windows-2019, windows-2022 ]
        runtime: [ static, dynamic ]
        ltcg: [ NoLTCG, LTCG ]
        pch: [ NoPCH, PCH ]
        debug: [ Zi, Z7 ]
        warning: [ NoWX, WX ]
        pdb: [ FASTLINK, FULL ]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSVC Environment
      uses: mbeckh/msvc-dev-cmd@master

    - name: Configure
      shell: cmd
      run: cmake -DCMAKE_BUILD_TYPE=Release -DOPTION_RUNTIME=${{matrix.runtime}} -DOPTION_LTCG=${{matrix.ltcg}} -DOPTION_PCH=${{matrix.pch}} -DOPTION_LTCG=${{matrix.debug}} -DOPTION_WARNING=${{matrix.warning}} -DOPTION_WARNING=${{matrix.warning}} -DOPTION_PDB=${{matrix.pdb}} -G Ninja -S "${{inputs.source-dir}}" -B build

    - name: Build
      shell: cmd
      working-directory: build
      run: cmake --build . -v
