name: build

on:
  push:
    branches: [ master, 'feature**' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2019, windows-2022 ]
        runtime: [ dynamic, static ]
        ltcg: [ NoLTCG, LTCG ]
        pch: [ NoPCH, PCH ]
        debug: [ Zi, Z7 ]
        warning: [ NoWX, WX ]
        pdb: [ NONE, FASTLINK, FULL ]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSVC Environment
      uses: mbeckh/msvc-dev-cmd@master

    - name: Configure
      shell: cmd
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -DOPTION_RUNTIME=${{matrix.runtime}} -DOPTION_LTCG=${{matrix.ltcg}} -DOPTION_PCH=${{matrix.pch}} -DOPTION_DEBUG=${{matrix.debug}} -DOPTION_WARNING=${{matrix.warning}} -DOPTION_PDB=${{matrix.pdb}} -G Ninja -S "${{inputs.source-dir}}" -B build

    - name: Build
      shell: cmd
      timeout-minutes: 5
      working-directory: build
      run: |
        mkdir ${{ github.workspace }}\linkrepro
        set link_repro=${{ github.workspace }}\linkrepro
        cmake --build . -v
    
    - name: Save Log
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2.2.4
      with: 
        name: linkrepro-${{matrix.os}}-${{matrix.runtime}}-${{matrix.ltcg}}-${{matrix.pch}}-${{matrix.debug}}-${{matrix.warning}}-${{matrix.pdb}}
        path: ${{ github.workspace }}/linkrepro
